
import { supabase } from '@/lib/supabaseClient';
import type { Category } from '@/types';

export const fetchCategoriesService = async (): Promise<Category[]> => {
    const { data, error } = await supabase
        .from('categories')
        .select('*');

    if (error) {
        console.error('Error fetching categories:', error);
        throw error;
    }

    return (data || []).map((c: any) => ({
        id: c.id || `cat-missing-${Math.random().toString(36).substring(2, 7)}`,
        name: c.name || 'Sem nome',
        imageUrl: c.image_url || '',
        totalRevenue: c.total_revenue ? Number(c.total_revenue) : 0,
        parentId: c.parent_id || undefined,
        type: (c.type as any) || 'supplement'
    }));
};

export const createCategoryService = async (category: Partial<Category>): Promise<Category | null> => {
    const dbPayload = {
        name: category.name,
        image_url: category.imageUrl,
        parent_id: category.parentId, // Add parent_id
        type: category.type || 'supplement', // Add type
        // id autogenerated or passed if needed
        id: category.id || `cat-${Date.now()}`
    };

    const { data, error } = await supabase
        .from('categories')
        .insert([dbPayload])
        .select()
        .single();

    if (error) {
        console.error('Error creating category:', error);
        throw error;
    }

    return {
        id: data.id,
        name: data.name,
        imageUrl: data.image_url,
        totalRevenue: data.total_revenue ? Number(data.total_revenue) : 0,
        parentId: data.parent_id,
        type: data.type
    };
};

export const updateCategoryService = async (category: Category): Promise<void> => {
    const dbPayload = {
        name: category.name,
        image_url: category.imageUrl,
        parent_id: category.parentId,
        type: category.type
    };

    const { error } = await supabase
        .from('categories')
        .update(dbPayload)
        .eq('id', category.id);

    if (error) {
        console.error('Error updating category:', error);
        throw error;
    }
};

export const deleteCategoryService = async (categoryId: string): Promise<void> => {
    const { error } = await supabase
        .from('categories')
        .delete()
        .eq('id', categoryId);

    if (error) {
        console.error('Error deleting category:', error);
        throw error;
    }
};
