
import { supabase } from '@/lib/supabaseClient';
import type { Product, Review } from '@/types';

// Helper to map DB snake_case to Product interface camelCase
const mapProductFromDB = (dbProduct: any): Product => {
    return {
        id: dbProduct.id,
        name: dbProduct.name,
        description: dbProduct.description,
        price: Number(dbProduct.price), // Ensure number
        originalPrice: dbProduct.original_price ? Number(dbProduct.original_price) : undefined,
        categoryId: dbProduct.category_id,
        category: dbProduct.categories?.name || dbProduct.category_id, // Join or raw ID fallback
        brand: dbProduct.brand,
        imageUrl: dbProduct.image_url,
        hoverImageUrl: dbProduct.hover_image_url,
        stock: dbProduct.stock,
        barcode: dbProduct.barcode,
        rating: Number(dbProduct.rating),
        salesCount: dbProduct.sales_count,
        isNewRelease: dbProduct.is_new_release,
        sizes: dbProduct.sizes || [],   // Added mapping
        colors: dbProduct.colors || [], // Added mapping
        flavors: dbProduct.flavors || [], // Added mapping
        // Reviews not fetched by default on list, maybe separate
        reviews: []
    };
};

export const fetchProductsService = async (): Promise<Product[]> => {
    const { data, error } = await supabase
        .from('products')
        .select(`
      *,
      categories (
        name
      )
    `)
    // .order('created_at', { ascending: false }); // Column created_at does not exist in schema


    if (error) {
        console.error('Error fetching products:', error);
        throw error;
    }

    return (data || []).map(mapProductFromDB);
};

export const fetchProductByIdService = async (id: string): Promise<Product | null> => {
    const { data, error } = await supabase
        .from('products')
        .select(`
      *,
      categories (
        name
      ),
      reviews (*)
    `)
        .eq('id', id)
        .single();

    if (error) {
        console.error(`Error fetching product ${id}:`, error);
        return null;
    }

    const product = mapProductFromDB(data);
    // Map reviews if fetched
    if (data.reviews) {
        product.reviews = data.reviews.map((r: any) => ({
            id: r.id,
            author: r.author,
            rating: r.rating,
            comment: r.comment,
            date: r.date
        }));
    }

    return product;
};

export const createProductService = async (product: Partial<Product>): Promise<Product | null> => {
    // Basic validation or default mapping
    const dbPayload = {
        name: product.name,
        description: product.description,
        price: product.price,
        original_price: product.originalPrice,
        category_id: product.categoryId, // Must be ID
        brand: product.brand,
        image_url: product.imageUrl,
        hover_image_url: product.hoverImageUrl, // Added field
        stock: product.stock,
        is_new_release: product.isNewRelease,
        sizes: product.sizes,   // Added
        colors: product.colors,  // Added
        flavors: product.flavors // Added
        // id is usually generated by DB (uuid), but our schema expects TEXT ID. 
        // If we generate in frontend, pass it here. If not, generate uuid.
        // For now, let's assume valid ID or generate one if missing.
    };

    // Add ID if provided (or generate simple one if missing/needed by schema constraints)
    const payloadWithId = { ...dbPayload, id: product.id || crypto.randomUUID() };

    const { data, error } = await supabase
        .from('products')
        .insert([payloadWithId])
        .select()
        .single();

    if (error) {
        console.error('Error creating product:', error);
        throw error;
    }

    // Hack: We need category NAME for the UI, but insert result won't join categories immediately usually?
    // Supabase .select('*, categories(name)') works on insert too if named right.
    return { ...mapProductFromDB(data), category: product.category || 'Nova Categoria' }; // Fallback name
};


export const updateProductService = async (product: Product): Promise<void> => {
    const dbPayload = {
        name: product.name,
        description: product.description,
        price: product.price,
        original_price: product.originalPrice,
        category_id: product.categoryId,
        brand: product.brand,
        image_url: product.imageUrl,
        hover_image_url: product.hoverImageUrl, // Added field
        stock: product.stock,
        is_new_release: product.isNewRelease,
        sizes: product.sizes,   // Added
        colors: product.colors,  // Added
        flavors: product.flavors // Added
    };

    const { error } = await supabase
        .from('products')
        .update(dbPayload)
        .eq('id', product.id);

    if (error) {
        console.error('Error updating product:', error);
        throw error;
    }
};

export const deleteProductService = async (productId: string): Promise<void> => {
    const { error } = await supabase
        .from('products')
        .delete()
        .eq('id', productId);

    if (error) {
        console.error('Error deleting product:', error);
        throw error;
    }
};

