-- Migration to secure RLS policies (Robust Version)
-- Generated by Antigravity

-- 1. Dynamic Drop of ALL existing policies for target tables
-- This ensures we start with a clean slate, removing any "hidden" permissive policies.
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public' 
        AND tablename IN (
            'integration_settings', 
            'carts', 
            'orders', 
            'order_items', 
            'products', 
            'categories', 
            'promotions', 
            'reviews', 
            'coupons', 
            'partners'
        )
    ) LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', r.policyname, r.tablename);
    END LOOP;
END $$;

-- 2. Apply Strict Policies

-- === INTGERATION SETTINGS ===
-- Strict: Backend (Service Role) only.
CREATE POLICY "Service Role manages integration_settings" ON public.integration_settings
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === CARTS ===
-- Strict: Service Role + Owners
CREATE POLICY "Service Role manages carts" ON public.carts
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Users can read own carts" ON public.carts
    FOR SELECT TO authenticated
    USING (user_email = (auth.jwt() ->> 'email'));

CREATE POLICY "Users can update own carts" ON public.carts
    FOR UPDATE TO authenticated
    USING (user_email = (auth.jwt() ->> 'email'));

CREATE POLICY "Users can insert own carts" ON public.carts
    FOR INSERT TO authenticated
    WITH CHECK (user_email = (auth.jwt() ->> 'email'));

-- === PRODUCTS ===
-- Strict: Public Read, Service Role Write
CREATE POLICY "Public read products" ON public.products
    FOR SELECT TO public USING (true);

CREATE POLICY "Service Role manages products" ON public.products
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === CATEGORIES ===
-- Strict: Public Read, Service Role Write
CREATE POLICY "Public read categories" ON public.categories
    FOR SELECT TO public USING (true);

CREATE POLICY "Service Role manages categories" ON public.categories
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === PROMOTIONS ===
-- Strict: Public Read, Service Role Write
CREATE POLICY "Public read promotions" ON public.promotions
    FOR SELECT TO public USING (true);

CREATE POLICY "Service Role manages promotions" ON public.promotions
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === REVIEWS ===
-- Strict: Public Read, Authenticated Insert, Service Role Manage
CREATE POLICY "Public read reviews" ON public.reviews
    FOR SELECT TO public USING (true);

CREATE POLICY "Authenticated insert reviews" ON public.reviews
    FOR INSERT TO authenticated WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Service Role manages reviews" ON public.reviews
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === COUPONS ===
-- Strict: Public Read, Service Role Write
CREATE POLICY "Public read coupons" ON public.coupons
    FOR SELECT TO public USING (true);

CREATE POLICY "Service Role manages coupons" ON public.coupons
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === PARTNERS ===
-- Strict: Public Read, Service Role Write
CREATE POLICY "Public read partners" ON public.partners
    FOR SELECT TO public USING (true);

CREATE POLICY "Service Role manages partners" ON public.partners
    FOR ALL TO service_role USING (true) WITH CHECK (true);

-- === ORDERS ===
-- Strict: Service Role + Owners (checking auth.uid)
CREATE POLICY "Service Role manages orders" ON public.orders
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Users can read own orders" ON public.orders
    FOR SELECT TO authenticated
    USING (auth.uid()::text = user_id);

-- === ORDER ITEMS ===
-- Strict: Service Role + Owners (via parent order)
CREATE POLICY "Service Role manages order_items" ON public.order_items
    FOR ALL TO service_role USING (true) WITH CHECK (true);

CREATE POLICY "Users can read own order items" ON public.order_items
    FOR SELECT TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM public.orders
            WHERE orders.id = order_items.order_id
            AND orders.user_id = auth.uid()::text
        )
    );
